// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_Uz_tLy-C1Re8pAwsiC4gMuel64QOEeY',
    appId: '1:421068310848:web:daf17cd791c4028d9a92a5',
    messagingSenderId: '421068310848',
    projectId: 'alihjenjangpnp',
    authDomain: 'alihjenjangpnp.firebaseapp.com',
    storageBucket: 'alihjenjangpnp.appspot.com',
    measurementId: 'G-VZZFW5SN72',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBf5SVfA9XTs_8gXPt045C6S2cX7Qzu_1c',
    appId: '1:421068310848:android:74496d1073c4c8fa9a92a5',
    messagingSenderId: '421068310848',
    projectId: 'alihjenjangpnp',
    storageBucket: 'alihjenjangpnp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3_K_e0n5CUUkz0AVmFO59oahSLMlDeao',
    appId: '1:421068310848:ios:eb0d512495ad36749a92a5',
    messagingSenderId: '421068310848',
    projectId: 'alihjenjangpnp',
    storageBucket: 'alihjenjangpnp.appspot.com',
    iosBundleId: 'com.example.testfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3_K_e0n5CUUkz0AVmFO59oahSLMlDeao',
    appId: '1:421068310848:ios:eb0d512495ad36749a92a5',
    messagingSenderId: '421068310848',
    projectId: 'alihjenjangpnp',
    storageBucket: 'alihjenjangpnp.appspot.com',
    iosBundleId: 'com.example.testfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_Uz_tLy-C1Re8pAwsiC4gMuel64QOEeY',
    appId: '1:421068310848:web:72bd0b69d0cc8a9e9a92a5',
    messagingSenderId: '421068310848',
    projectId: 'alihjenjangpnp',
    authDomain: 'alihjenjangpnp.firebaseapp.com',
    storageBucket: 'alihjenjangpnp.appspot.com',
    measurementId: 'G-RVY16LHR5X',
  );

}